//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bluff
    {
        public int Id { get; set; }
        public int BlufferId { get; set; }
        public string CardBluffed { get; set; }
        public bool BluffCalled { get; set; }
        public Nullable<int> CalledById { get; set; }
        public int GameId { get; set; }
    
        public virtual Player MadeBy { get; set; }
        public virtual Player CalledBy { get; set; }
        public virtual Game Game { get; set; }
    }
}
